server:
  host: 172.16.16.46:9999
  name: Rattrap-Distribution-Server
rocketMQ:
  nameServer: 172.16.16.37:9876
  groupName: rattrap-mq
  consumerGroupName: consumer-rattrap-mq
database:
  host: 172.16.16.46
  port: 15432
  userName: rattrap
  password: rattrap123456
  dbName: rattrap
redis:
  address: 127.0.0.1:6379
  password: ""
  db: 0